name: Build and Deploy to Azure Web App

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: 
      group: deploy-${{ github.ref }}
      cancel-in-progress: true  # Critical fix for 409 conflicts

    steps:
      - name: ⏬ Checkout code
        uses: actions/checkout@v3

      - name: 🔐 Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Verify Azure Access
        run: az webapp list --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }}

      - name: ⚙️ Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 📦 Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧹 Clean Kudu Deployment Cache
        run: |
          az webapp deployment source delete \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \

      - name: 🚀 Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: production
          package: .
          # Add explicit token for deployments
          token: ${{ secrets.GITHUB_TOKEN }}  # Add this line